### ISSUE TITLE
Support kana input in search boxes

### ISSUE THREAD

**Issue by Wazhai** [Spugn/priconne-quest-helper#1]
Feature request:

It would be very handy if search didn't care about katakana vs hiragana and accepted both as is customary in most Japanese applications. Katakana and hiragana have a 1:1 correspondence between each others' symbols.

![Screenshot_20221229_035237_Firefox](https://user-images.githubusercontent.com/14195241/209898166-1a11699e-88bc-4db8-9d9e-d0e9d71906a3.png)
![Screenshot_20221229_035256_Firefox](https://user-images.githubusercontent.com/14195241/209898177-893660e0-aca7-44c5-b423-b9877d1d3767.png)

**Comment by Expugn** [comment]
Added as of <https://github.com/Spugn/priconne-quest-helper/commit/4a2c325adf2566c6f7b9ad5a0fbbf744b6b56a91>, thanks!
