### ISSUE TITLE
Latin input for character names only works for global-released ones

### ISSUE THREAD

**Issue by Wazhai** [Spugn/priconne-quest-helper#2]
**Expected behavior**
Latin input for character names should ideally work for all character alts.

**Screenshots**
![Screenshot_20221229_040008_Firefox](https://user-images.githubusercontent.com/14195241/209898377-34143e0a-0446-4fa5-9a13-2784d3f145e0.png)
![Screenshot_20221229_040022_Firefox](https://user-images.githubusercontent.com/14195241/209898385-fca0ab2c-93dc-4aea-82c0-ee903bb859d2.png)

**Comment by Wazhai** [comment]
This can be automated fully by using matching data from other entries to fall back to if a field is empty. For example:
```
Language 	Name
JP 	ヒヨリ
CN 	日和莉
EN 	Hiyori
KR 	히요리
TW 	日和
```
Ignoring text in brackets, Summer Hiyori has ヒヨリ in common with regular Hiyori...
```
Language 	Name
JP 	ヒヨリ（サマー）
TW 	日和（夏日）
```
So sHiyori can be filled out automatically like this:
```
Language 	Name
JP 	ヒヨリ（サマー）
TW 	日和（夏日）
[ CN 	日和莉 ]
[ EN 	Hiyori ]
[ KR 	히요리 ]
```

Further, things in brackets like （サマー） will be common to all Summer variants so those can be inferred as well until it appears in the official data.
```
[ EN 	Hiyori (Summer) ]
```

**Comment by Expugn** [comment]
Added as of <https://github.com/Spugn/priconne-quest-helper/commit/4a2c325adf2566c6f7b9ad5a0fbbf744b6b56a91>, thanks!

Although potential automation method isn't exactly used...
`Romanji to Kana` has been added, so searching someone like "`hiyori`" will return future thematics of Hiyori as well now.
A flaw in this current implementation is that a drastically different officially translated name (e.g. Karyl) won't return later thematics (although "`Kyaru`" will work fine now)
Also thematics that are totally different (e.g. Holiday) won't work, but you can search for "`kurisumasu`" now.

If this continues to be an inconvenience then I'll revisit this at a later date, but for now it's pretty low priority.
