### ISSUE TITLE
Improvements for alternative inventory mode

### ISSUE THREAD

**Issue by Wazhai** [Spugn/priconne-quest-helper#3]
**Is your feature request related to a problem? Please describe.**
Right now alternative inventory mode displays everything in a fixed order.

**Describe the solution you'd like**
* Sorting can be reversed
* Option to hide undesired item rarities and character shards

There could be a couple of buttons on top similar to default inventory mode.

**Comment by Expugn** [comment]
Added as of <https://github.com/Spugn/priconne-quest-helper/commit/4a2c325adf2566c6f7b9ad5a0fbbf744b6b56a91>, thanks!
