### ISSUE TITLE
Impossible to backspace below minimum rank

### ISSUE THREAD

**Issue by Wazhai** [Spugn/priconne-quest-helper#4]
**Describe the bug**
If a project's start rank is e.g. 20 and I try to backspace and change the end rank to 26, it's impossible because the input box doesn't let it go below 20 down to 2 so that 26 can be input 

**To Reproduce**
1. Set start rank 20
2. Try to backspace in end rank input box and input 26
3. I can't in all the browsers I tried

**Expected behavior**
Input boxes should allow any number to be input and only "correct" invalid values once it loses focus.

**Additional context**
Adjustment arrows on the right bypass this, but a better solution would be great.

**Comment by Expugn** [comment]
Changed/fixed as of <https://github.com/Spugn/priconne-quest-helper/commit/4a2c325adf2566c6f7b9ad5a0fbbf744b6b56a91>, thanks!
