### ISSUE TITLE
Export text is displayed cut-off on narrow displays

### ISSUE THREAD

**Issue by Wazhai** [Spugn/priconne-quest-helper#5]
The URL should be wrapped at any symbol so that everything can fit. The other text also goes out of boundary.

![Screenshot_20221229_050602_Firefox](https://user-images.githubusercontent.com/14195241/209902177-bddd1653-adf4-42a2-8d54-debdc917ac82.png)

**Comment by Expugn** [comment]
Fixed as of <https://github.com/Spugn/priconne-quest-helper/commit/4a2c325adf2566c6f7b9ad5a0fbbf744b6b56a91>, thanks!
