### ISSUE TITLE
Don't focus Project Name field by default

### ISSUE THREAD

**Issue by Wazhai** [Spugn/priconne-quest-helper#6]
**Describe the bug**
There is an annoying behaviour for touchscreen devices because the Project Name input box gets focused when you open Edit Project. This opens the mobile keyboard every time for an optional field that I won't use.

**Expected behavior**
Project Name doesn't get focus after opening Edit Project. Users need to select this manually if they want to input a project name.

**Screenshots**
![Screenshot_20221229_163956_Firefox](https://user-images.githubusercontent.com/14195241/209976698-c2ea4b22-fa76-4795-b64a-fb5a5a136bc8.png)

**Comment by Expugn** [comment]
Added as of <https://github.com/Spugn/priconne-quest-helper/commit/e47a701c5eaa13b588a8707a013d8f501c5b23a9>, but I am personally unable to validate if the changes works or not.

I've tried on both a desktop browser and two mobile browsers but both don't autofocus the project name input (with and without new changes).
